package org.sibel.constants;

import org.somda.sdc.biceps.model.participant.AlertSignalManifestation;

public enum PhysiologicalAlertSignal {
    HR_HIGH__AUD(
            "258049",
            PhysiologicalAlertCondition.HR_HIGH,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.hr.high"),
    HR_HIGH__VIS(
            "258050",
            PhysiologicalAlertCondition.HR_HIGH,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.hr.high"),
    OLD_HR_HIGH__AUD(
            "258049",
            PhysiologicalAlertCondition.HR_ALL,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.hr.high.OLD"),
    OLD_HR_HIGH__VIS(
            "258050",
            PhysiologicalAlertCondition.HR_ALL,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.hr.high.OLD"),

    HR_LOW__AUD(
            "258053",
            PhysiologicalAlertCondition.HR_LOW,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.hr.low"),
    HR_LOW__VIS(
            "258054",
            PhysiologicalAlertCondition.HR_LOW,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.hr.low"),
    OLD_HR_LOW__AUD(
            "258053",
            PhysiologicalAlertCondition.HR_ALL,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.hr.low.OLD"),
    OLD_HR_LOW__VIS(
            "258054",
            PhysiologicalAlertCondition.HR_ALL,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.hr.low.OLD"),

    RR_HIGH__AUD(
            "258061",
            PhysiologicalAlertCondition.RR_HIGH,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.rr.high"),
    RR_HIGH__VIS(
            "258062",
            PhysiologicalAlertCondition.RR_HIGH,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.rr.high"),
    OLD_RR_HIGH__AUD(
            "258061",
            PhysiologicalAlertCondition.RR_ALL,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.rr.high.OLD"),
    OLD_RR_HIGH__VIS(
            "258062",
            PhysiologicalAlertCondition.RR_ALL,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.rr.high.OLD"),

    RR_LOW__AUD(
            "258057",
            PhysiologicalAlertCondition.RR_LOW,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.rr.low"),
    RR_LOW__VIS(
            "258058",
            PhysiologicalAlertCondition.RR_LOW,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.rr.low"),
    OLD_RR_LOW__AUD(
            "258057",
            PhysiologicalAlertCondition.RR_ALL,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.rr.low.OLD"),
    OLD_RR_LOW__VIS(
            "258058",
            PhysiologicalAlertCondition.RR_ALL,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.rr.low.OLD"),

    PR_HIGH__AUD(
            "258181",
            PhysiologicalAlertCondition.PR_HIGH,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.pr.high"),
    PR_HIGH__VIS(
            "258182",
            PhysiologicalAlertCondition.PR_HIGH,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.pr.high"),
    OLD_PR_HIGH__AUD(
            "258181",
            PhysiologicalAlertCondition.PR_ALL,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.pr.high.OLD"),
    OLD_PR_HIGH__VIS(
            "258182",
            PhysiologicalAlertCondition.PR_ALL,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.pr.high.OLD"),

    PR_LOW__AUD(
            "258177",
            PhysiologicalAlertCondition.PR_LOW,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.pr.low"),
    PR_LOW__VIS(
            "258178",
            PhysiologicalAlertCondition.PR_LOW,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.pr.low"),
    OLD_PR_LOW__AUD(
            "258177",
            PhysiologicalAlertCondition.PR_ALL,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.pr.low.OLD"),
    OLD_PR_LOW__VIS(
            "258178",
            PhysiologicalAlertCondition.PR_ALL,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.pr.low.OLD"),

    SPO2_HIGH__AUD(
            "258069",
            PhysiologicalAlertCondition.SPO2_HIGH,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.spo2.high"),
    SPO2_HIGH__VIS(
            "258070",
            PhysiologicalAlertCondition.SPO2_HIGH,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.spo2.high"),
    OLD_SPO2_HIGH__AUD(
            "258069",
            PhysiologicalAlertCondition.SPO2_ALL,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.spo2.high.OLD"),
    OLD_SPO2_HIGH__VIS(
            "258070",
            PhysiologicalAlertCondition.SPO2_ALL,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.spo2.high.OLD"),

    SPO2_LOW__AUD(
            "258065",
            PhysiologicalAlertCondition.SPO2_LOW,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.spo2.low"),
    SPO2_LOW__VIS(
            "258066",
            PhysiologicalAlertCondition.SPO2_LOW,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.spo2.low"),
    OLD_SPO2_LOW__AUD(
            "258065",
            PhysiologicalAlertCondition.SPO2_ALL,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.spo2.low.OLD"),
    OLD_SPO2_LOW__VIS(
            "258066",
            PhysiologicalAlertCondition.SPO2_ALL,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.spo2.low.OLD"),

    BODY_POSITION_HIGH__AUD(
            "258173",
            PhysiologicalAlertCondition.BODY_POSITION_HIGH,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.aud.bodyposition.high"),
    BODY_POSITION_HIGH__VIS(
            "258174",
            PhysiologicalAlertCondition.BODY_POSITION_HIGH,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.bodyposition.high"),

    OLD__BP_SYS_LOW__AUD(
            "258073",
            PhysiologicalAlertCondition.BP_SYS_ALL,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.bpsys.low.OLD"),
    OLD__BP_SYS_LOW__VIS(
            "258074",
            PhysiologicalAlertCondition.BP_SYS_ALL,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.bpsys.low.OLD"),
    BP_SYS_LOW__AUD(
            "258073",
            PhysiologicalAlertCondition.BP_SYS_LOW,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.bpsys.low"),
    BP_SYS_LOW__VIS(
            "258074",
            PhysiologicalAlertCondition.BP_SYS_LOW,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.bpsys.low"),

    OLD__BP_SYS_HIGH__AUD(
            "258077",
            PhysiologicalAlertCondition.BP_SYS_ALL,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.bpsys.high.OLD"),
    OLD__BP_SYS_HIGH__VIS(
            "258078",
            PhysiologicalAlertCondition.BP_SYS_ALL,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.bpsys.high.OLD"),
    BP_SYS_HIGH__AUD(
            "258077",
            PhysiologicalAlertCondition.BP_SYS_HIGH,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.bpsys.high"),
    BP_SYS_HIGH__VIS(
            "258078",
            PhysiologicalAlertCondition.BP_SYS_HIGH,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.bpsys.high"),

    OLD__BP_DIA_LOW__AUD(
            "258081",
            PhysiologicalAlertCondition.BP_DIA_ALL,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.bpdia.low.OLD"),
    OLD__BP_DIA_LOW__VIS(
            "258082",
            PhysiologicalAlertCondition.BP_DIA_ALL,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.bpdia.low.OLD"),
    BP_DIA_LOW__AUD(
            "258081",
            PhysiologicalAlertCondition.BP_DIA_LOW,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.bpdia.low"),
    BP_DIA_LOW__VIS(
            "258082",
            PhysiologicalAlertCondition.BP_DIA_LOW,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.bpdia.low"),

    OLD__BP_DIA_HIGH__AUD(
            "258085",
            PhysiologicalAlertCondition.BP_DIA_ALL,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.bpdia.high.OLD"),
    OLD__BP_DIA_HIGH__VIS(
            "258086",
            PhysiologicalAlertCondition.BP_DIA_ALL,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.bpdia.high.OLD"),
    BP_DIA_HIGH__AUD(
            "258085",
            PhysiologicalAlertCondition.BP_DIA_HIGH,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.bpdia.high"),
    BP_DIA_HIGH__VIS(
            "258086",
            PhysiologicalAlertCondition.BP_DIA_HIGH,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.bpdia.high"),

    OLD__BODY_TEMP_LOW__AUD(
            "258161",
            PhysiologicalAlertCondition.BODY_TEMP_ALL,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.bodytemp.low.OLD"),
    OLD__BODY_TEMP_LOW__VIS(
            "258162",
            PhysiologicalAlertCondition.BODY_TEMP_ALL,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.bodytemp.low.OLD"),
    BODY_TEMP_LOW__AUD(
            "258161",
            PhysiologicalAlertCondition.BODY_TEMP_LOW,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.bodytemp.low"),
    BODY_TEMP_LOW__VIS(
            "258162",
            PhysiologicalAlertCondition.BODY_TEMP_LOW,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.bodytemp.low"),

    OLD__BODY_TEMP_HIGH__AUD(
            "258165",
            PhysiologicalAlertCondition.BODY_TEMP_ALL,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.bodytemp.high.OLD"),
    OLD__BODY_TEMP_HIGH__VIS(
            "258166",
            PhysiologicalAlertCondition.BODY_TEMP_ALL,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.bodytemp.high.OLD"),
    BODY_TEMP_HIGH__AUD(
            "258165",
            PhysiologicalAlertCondition.BODY_TEMP_HIGH,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.bodytemp.high"),
    BODY_TEMP_HIGH__VIS(
            "258166",
            PhysiologicalAlertCondition.BODY_TEMP_HIGH,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.bodytemp.high"),

    OLD__CHEST_SKIN_TEMP_LOW__AUD(
            "258153",
            PhysiologicalAlertCondition.CHEST_SKIN_TEMP_ALL,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.chest.skintemp.low.OLD"),
    OLD__CHEST_SKIN_TEMP_LOW__VIS(
            "258154",
            PhysiologicalAlertCondition.CHEST_SKIN_TEMP_ALL,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.chest.skintemp.low.OLD"),
    CHEST_SKIN_TEMP_LOW__AUD(
            "258153",
            PhysiologicalAlertCondition.CHEST_SKIN_TEMP_LOW,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.chest.skintemp.low"),
    CHEST_SKIN_TEMP_LOW__VIS(
            "258154",
            PhysiologicalAlertCondition.CHEST_SKIN_TEMP_LOW,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.chest.skintemp.low"),

    OLD__CHEST_SKIN_TEMP_HIGH__AUD(
            "258157",
            PhysiologicalAlertCondition.CHEST_SKIN_TEMP_ALL,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.chest.skintemp.high.OLD"),
    OLD__CHEST_SKIN_TEMP_HIGH__VIS(
            "258158",
            PhysiologicalAlertCondition.CHEST_SKIN_TEMP_ALL,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.chest.skintemp.high.OLD"),
    CHEST_SKIN_TEMP_HIGH__AUD(
            "258157",
            PhysiologicalAlertCondition.CHEST_SKIN_TEMP_HIGH,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.chest.skintemp.high"),
    CHEST_SKIN_TEMP_HIGH__VIS(
            "258158",
            PhysiologicalAlertCondition.CHEST_SKIN_TEMP_HIGH,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.chest.skintemp.high"),

    OLD__LIMB_SKIN_TEMP_LOW__AUD(
            "258153",
            PhysiologicalAlertCondition.LIMB_SKIN_TEMP_ALL,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.limb.skintemp.low.OLD"),
    OLD__LIMB_SKIN_TEMP_LOW__VIS(
            "258154",
            PhysiologicalAlertCondition.LIMB_SKIN_TEMP_ALL,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.limb.skintemp.low.OLD"),
    LIMB_SKIN_TEMP_LOW__AUD(
            "258153",
            PhysiologicalAlertCondition.LIMB_SKIN_TEMP_LOW,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.limb.skintemp.low"),
    LIMB_SKIN_TEMP_LOW__VIS(
            "258154",
            PhysiologicalAlertCondition.LIMB_SKIN_TEMP_LOW,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.limb.skintemp.low"),

    OLD__LIMB_SKIN_TEMP_HIGH__AUD(
            "258157",
            PhysiologicalAlertCondition.LIMB_SKIN_TEMP_ALL,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.limb.skintemp.high.OLD"),
    OLD__LIMB_SKIN_TEMP_HIGH__VIS(
            "258158",
            PhysiologicalAlertCondition.LIMB_SKIN_TEMP_ALL,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.limb.skintemp.high.OLD"),
    LIMB_SKIN_TEMP_HIGH__AUD(
            "258157",
            PhysiologicalAlertCondition.LIMB_SKIN_TEMP_HIGH,
            AlertSignalManifestation.AUD,
            "sibel.anneone.alertsystem.signal.aud.limb.skintemp.high"),
    LIMB_SKIN_TEMP_HIGH__VIS(
            "258158",
            PhysiologicalAlertCondition.LIMB_SKIN_TEMP_HIGH,
            AlertSignalManifestation.VIS,
            "sibel.anneone.alertsystem.signal.vis.limb.skintemp.high");

    public final String code;
    public final PhysiologicalAlertCondition condition;
    public final AlertSignalManifestation manifestation;
    public final String handle;

    PhysiologicalAlertSignal(
            String code, PhysiologicalAlertCondition condition, AlertSignalManifestation manifestation, String handle) {
        this.code = code;
        this.condition = condition;
        this.manifestation = manifestation;
        this.handle = handle;
    }
}
