image:
  repository: 620908046246.dkr.ecr.us-east-2.amazonaws.com/authentication
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: ecr

app:
  config:
    ENVIRONMENT: "prod"
    DEFAULT_CLINICAL_EMAIL: "admin@sibelhealth.com"
    DEFAULT_CLINICAL_USERNAME: "admin@sibelhealth.com"