@startuml Clinical Change Password
!include <C4/C4_Component>

actor       "Clinical User"  as user
participant "Central Monitoring Site" as cms
participant "Web Gateway" as web

cms -> cms : Loads Clinical Module
user -> cms : Clicks on Settings button
cms -> user : Shows Settings Sidebar
user -> cms : Clicks Change Password Button
cms -> user : Prompts user to enter old password
user -> cms : Enters password and confirms
cms -> web : Requests password validation
web -> cms : Returns password is valid
cms -> user : Shows Change Password Modal
loop while new password information has not been confirmed
user -> cms : Enters new password and repeats it
alt password information is invalid
    cms -> user : Shows error message
end
cms -> web : Requests password change
web -> user : Returns password change success
cms -> user : Shows password changed modal
user -> cms : Acknowledges the change by clicking "OK"

@enduml