@startuml Display Realtime Vitals
!include <C4/C4_Component>

participant "Central Monitoring Site" as cms
participant "Web Worker" as worker
participant "Realtime Gateway" as realtime
participant "Web Gateway" as web

cms -> web : Request current groups patients
web -> cms : Returns current groups patients
cms -> worker : Starts worker with group patients
worker -> realtime : Establishes realtime connection

loop while connection is established
    realtime -> worker : Sends realtime vitals data for selected patients
    worker -> cms : Passes realtime data along
    cms -> cms : Displays realtime data for current group
end

cms -> worker : Sends disconnection message
worker -> realtime : Finishes connection

@enduml