@startuml Update beds
!include <C4/C4_Component>

actor       "Clinical User"  as user
participant "Central Monitoring Site" as cms
participant "Web Gateway" as web

cms -> user : Shows Bed Management Modal (Step 1)
loop while more edits are needed
    user -> cms : Adds/Removes/Edits a bed
    alt two beds have the same id
        cms -> user : shows error on both beds
        cms -> cms : deactivates save button
    else bed has an empty id
        cms -> user : shows error on empty id bed
        cms -> cms : deactivates save button
    else no errors found
        cms -> cms : activates save button
    end
end
user -> cms : Presses save button
cms -> web : Adds new beds and updates old beds
web -> cms : Returns sucess message
cms -> web : Deletes beds removed by user
web -> cms : Return sucess message
cms -> user : Shows Bed Management Modal (Step 2) 


@enduml