@startuml Change password
start
if (Is the user's account locked?) is (yes) then
    :Return an error;
else (no)
    if (Is the user's current password correct?) is (no) then
        :Increment the user's auth attempts;
        if (Max auth attempts reached?) is (yes) then
            :Temporarily lock user account;
            :Notify user locked to event bus;
        else (no)
            :Notify user auth attempt to event bus;
        endif
        :Return an error;
    else (yes)
        :Update user password;
        :Notify user modified to event bus;
    endif
    
endif

stop
@enduml
