name: Cloud - generic deploy
run-name: Cloud - deploy to ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        required: true
        default: 'qa'

jobs:
  projects-to-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.11.9

      - name: Install Poetry
        run: pip3 install poetry

      - name: Install build tools
        run: poetry install
        working-directory: ./scripts/buildtools

      - name: Detect updated projects - CI
        run: |
          poetry run buildtools get-projects changed-projects.json \
          --deployable
        working-directory: ./scripts/buildtools

      - name: Setup Matrix environment
        id: set_matrix
        uses: juliangruber/read-file-action@v1
        with:
          path: ./scripts/buildtools/changed-projects.json

    outputs:
      matrix: ${{ steps.set_matrix.outputs.content }}

  build-projects:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs:
      - projects-to-build
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix: ${{ fromJson(needs.projects-to-build.outputs.matrix) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.11.9

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}
          role-session-name: AWS-DEPLOYMENT-SESSION

      - name: Login to Amazon ECR
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        working-directory: ${{ matrix.path }}
        env:
          REGISTRY: ${{ steps.login_ecr.outputs.registry }}
          REPOSITORY: ${{ matrix.name }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo $REGISTRY/$REPOSITORY
          echo $REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo $REGISTRY/$REPOSITORY:latest
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest --build-arg REGISTRY_NAME=$REGISTRY --build-arg SIBEL_VERSION=$IMAGE_TAG -f Dockerfile ../../.
          docker push --all-tags $REGISTRY/$REPOSITORY

  deploy-projects:
    runs-on:
      - self-hosted
      - k8s
      - ${{ inputs.environment }}
    needs:
      - projects-to-build
      - build-projects
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix: ${{ fromJson(needs.projects-to-build.outputs.matrix) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.11.2'

      - name: Deploy ${{ matrix.name }}
        working-directory: ${{ matrix.path }}
        env:
          REPOSITORY: ${{ matrix.name }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo $REPOSITORY
          echo $REPOSITORY:$IMAGE_TAG
          echo $KUBECONFIG | base64 -d > kubeconfig
          helm upgrade -i $REPOSITORY ./deploy -f ./deploy/values.${{ inputs.environment }}.yaml --set image.tag=$IMAGE_TAG --kubeconfig=kubeconfig
