name: Cloud - Infra Base PROD

concurrency:
  group: ${{ github.ref }}-prod-infra
  cancel-in-progress: true

on:
  push:
    branches:
      - develop
    paths:
      - "infra/modules/core/**"
      - "infra/modules/k8s/**"
      - "infra/prod/tf/**"

  pull_request:
    branches:
      - "develop"
    paths:
      - "infra/modules/core/**"
      - "infra/modules/k8s/**"
      - "infra/prod/tf/**"
      - '!infra/prod/k8s-infra-apps/**'

jobs:
  terraform-plan-base-infra:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: prod
    concurrency: terraform-prod
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN_PROD }}
          role-session-name: tucana-prod

      - name: Terraform Format
        id: tf_format
        run: terraform fmt -check
        working-directory: ./infra/prod/tf

      - name: Terraform Init
        id: tf_init
        run: terraform init
        working-directory: ./infra/prod/tf

      - name: Terraform Validate
        id: tf_validate
        run: terraform validate -no-color
        working-directory: ./infra/prod/tf

      - name: Terraform Plan
        id: tf_plan
        run: |
          terraform plan -no-color -input=false -out=plan.tmp
          terraform show -no-color plan.tmp >${GITHUB_WORKSPACE}/plan.out
        continue-on-error: true
        working-directory: ./infra/prod/tf

      - name: Update Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const run_url = process.env.GITHUB_SERVER_URL + '/' + process.env.GITHUB_REPOSITORY + '/actions/runs/' + process.env.GITHUB_RUN_ID
            const run_link = '<a href="' + run_url + '">Actions</a>.'
            const fs = require('fs')
            const plan_file = fs.readFileSync('plan.out', 'utf8')
            const plan = plan_file.length > 65000 ? plan_file.toString().substring(0, 65000) + " ..." : plan_file
            const truncated_message = plan_file.length > 65000 ? "Output is too long and was truncated. You can read full Plan in " + run_link + "<br /><br />" : ""
            const output = `#### Terraform Format and Style 🖌\`${{ steps.tf_format.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.tf_init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.tf_plan.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.tf_validate.outcome }}\`
            <details><summary>Show Plan</summary>
            \`\`\`\n
            ${plan}
            \`\`\`
            </details>

            ${truncated_message}
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: Terraform Plan Status
        if: steps.tf_plan.outcome == 'failure'
        run: exit 1

  terraform-apply-base-infra:
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: prod
    concurrency: terraform-prod
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN_PROD }}

      - name: Terraform Format
        id: tf_format
        run: terraform fmt -check
        working-directory: ./infra/prod/tf

      - name: Terraform Init
        id: tf_init
        run: terraform init
        working-directory: ./infra/prod/tf

      - name: Deploy base infra
        id: deploy_base_infra
        run: terraform apply -auto-approve -input=false
        working-directory: ./infra/prod/tf