name: Tagged Release

on:
  push:
    tags:
      - CLOUDT-1030

permissions: write-all

jobs:
  projects-to-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.11.9

      - name: Install Poetry
        run: pip3 install poetry

      - name: Install build tools
        run: poetry install
        working-directory: ./scripts/buildtools

  build-offline-installation-image:
    needs:
      - projects-to-build
    runs-on:
      - self-hosted
      - k8s
      - prod
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Prepare infrastructure images for offline installation
        run: |
          mkdir -p ${{ github.workspace }}/infra/setup/installation-pack/images
          echo "hello chirag" >> ${{ github.workspace }}/infra/setup/installation-pack/images/test.txt

      - name: Upload offline image to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: central-hub-images
          path: ${{ github.workspace }}/infra/setup/installation-pack/images/

  build-online-installation-image:
    needs:
      - projects-to-build
      - build-offline-installation-image
    runs-on:
      - self-hosted
      - k8s
      - prod
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Download central hub image artifacts
        uses: actions/download-artifact@v4
        with:
          name: central-hub-images
          path: ${{ github.workspace }}/infra/setup/installation-pack/

      - name: Prepare infrastructure images for offline installation
        run: |
          ls -l ${{ github.workspace }}/infra/setup/installation-pack
