name: Tagged Release

on:
  push:
    tags:
      - CLOUDT-1030

permissions: write-all

jobs:
  projects-to-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.11.9

      - name: Install Poetry
        run: pip3 install poetry

      - name: Install build tools
        run: poetry install
        working-directory: ./scripts/buildtools

  build-offline-installation-image:
    needs:
      - projects-to-build
    runs-on:
      - self-hosted
      - k8s
      - prod
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Start local Docker registry
        run: |
          docker run --restart=always -d -p 5000:5000 --name image-registry registry:2
          docker buildx create --name mybuilder --use --driver docker-container
          docker buildx inspect --bootstrap
